filepath: '.../SyntheticDriving'

train_dataset:
  _target_: datasets.VoxelDrivingDataset
  datapath: ${dataloader.dataset.filepath}
  list_filename: '.../ODTFormer/filenames/Driving_vox_train.txt'
  training: True
  roi_scale: ${dataloader.roi}
  voxel_sizes: ${dataloader.vox}
  transform: True
  color_jitter: True
  filter_ground: True
  resize_shape: ${dataloader.resize_shape}

test_dataset:
  _target_: datasets.VoxelDrivingDataset
  datapath: ${dataloader.dataset.filepath}
  list_filename: '.../ODTFormer/filenames/Driving_vox_test.txt'
  training: False
  roi_scale: ${dataloader.roi}
  voxel_sizes: ${dataloader.vox}
  transform: True
  filter_ground: True
  resize_shape: ${dataloader.resize_shape}