filepath: '.../KITTI_VoxelFlow'

train_dataset:
  _target_: datasets.VoxelKITTIRaw
  datapath: ${dataloader.dataset.filepath}
  list_filename: '.../ODTFormer/filenames/KITTI_raw.txt'
  training: True
  roi_scale: ${dataloader.roi}
  voxel_sizes: ${dataloader.vox}
  transform: True
  color_jitter: True
  filter_ground: True
  resize_shape: ${dataloader.resize_shape}

test_dataset:
  _target_: datasets.VoxelKITTIDataset
  datapath: ${dataloader.dataset.filepath}
  list_filename: '.../ODTFormer/filenames/KITTI_vox.txt'
  training: False
  roi_scale: ${dataloader.roi}
  voxel_sizes: ${dataloader.vox}
  transform: True
  filter_ground: True
  resize_shape: ${dataloader.resize_shape}