defaults:
  - model: odtformer
  - dataloader: kitti_dataloader
  - trainer: trainer_full
  - optimizer: adamw
  - dist: ddp
  - override hydra/hydra_logging: disabled
  - _self_

use_wandb: True
# Don't create hydra output directories
hydra:
  output_subdir: ~
  run:
    dir: .

